image: gitpod/workspace-node-18

tasks:
  - name: Install ServiceNow CLI
    init: |
      wget https://github.com/ServiceNow/servicenow-cli/releases/download/v1.1.3/snc-1.1.3-linux-x64-installer.run -O /tmp/snc-installer.run
      chmod +x /tmp/snc-installer.run
      sudo /tmp/snc-installer.run --mode unattended
      npm install -g @servicenow/cli
    command: echo "Environment ready! Type 'snc' to begin."
    
vscode:
  extensions:
    - ServiceNow.now-vscode